# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivoCod', models.CharField(max_length=15, unique=True)),
                ('motivoNombre', models.CharField(max_length=50)),
                ('ConsumoMonto', models.FloatField(blank=True)),
                ('ConsumoVeces', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocionCod', models.CharField(max_length=15, unique=True)),
                ('promocionNombre', models.CharField(max_length=50)),
                ('promocionDescripcion', models.CharField(max_length=80)),
                ('promocionInicio', models.DateTimeField()),
                ('promocionFin', models.DateTimeField()),
                ('promocionTipoC', models.CharField(max_length=1)),
                ('promocionEstado', models.CharField(max_length=1)),
                ('motivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Promocion.Motivo')),
            ],
        ),
        migrations.CreateModel(
            name='PromocionDescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuentoCod', models.CharField(max_length=15, unique=True)),
                ('descuentoPorcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PromocionVale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocionValeCod', models.CharField(max_length=15, unique=True)),
                ('promocionValeNombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='promocion',
            name='promocionDescuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Promocion.PromocionDescuento'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='promocionVale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Promocion.PromocionVale'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='sucursal',
            field=models.ManyToManyField(to='Sucursal.Sucursal'),
        ),
    ]
