# Generated by Django 2.0.6 on 2018-06-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promocion', '0002_motivo_motivotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='motivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Promocion.Motivo'),
        ),
    ]
