# Generated by Django 2.0.6 on 2018-07-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promocion', '0003_auto_20180626_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='motivo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Promocion.Motivo'),
        ),
    ]
