# Generated by Django 2.0.7 on 2018-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promocion', '0006_promocion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
