# Generated by Django 2.0.7 on 2018-07-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promocion', '0007_auto_20180716_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='promocionDescuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Promocion.PromocionDescuento'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='promocionVale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Promocion.PromocionVale'),
        ),
    ]
