# Generated by Django 2.0.7 on 2018-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promocion', '0008_auto_20180723_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='habilitar',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='publicar',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
