# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipovehiculoCod', models.CharField(max_length=15, unique=True)),
                ('tipovehiculoDescripcion', models.CharField(max_length=50)),
                ('tipovehiculoEstado', models.CharField(choices=[('A', 'activo'), ('I', 'inactivo')], max_length=1)),
            ],
        ),
    ]
