# Generated by Django 2.0.4 on 2018-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoriaEstado',
            field=models.CharField(max_length=1),
        ),
    ]
