# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustibleCod', models.CharField(max_length=15, unique=True)),
                ('combustibleNombre', models.CharField(max_length=50)),
                ('combustibleDescripcion', models.CharField(max_length=80)),
                ('combustiblePrecioUnidad', models.FloatField()),
                ('combustibleEstado', models.CharField(choices=[('A', 'activo'), ('I', 'inactivo')], max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Categoria.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoCod', models.CharField(max_length=15, unique=True)),
                ('productoNombre', models.CharField(max_length=50)),
                ('productoDescripcion', models.CharField(max_length=50)),
                ('productoPrecio', models.FloatField(default=None)),
                ('productoEstado', models.CharField(choices=[('A', 'activo'), ('I', 'inactivo')], max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Categoria.Categoria')),
            ],
        ),
    ]
