# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilegioCod', models.CharField(max_length=15, unique=True)),
                ('privilegioDescripcion', models.CharField(max_length=80)),
                ('privilegioRecurso', models.CharField(max_length=150)),
                ('privilegioDependencia', models.IntegerField()),
                ('privilegioEstado', models.CharField(max_length=1)),
                ('privilegioIcono', models.CharField(max_length=60)),
            ],
        ),
    ]
