# Generated by Django 2.0.4 on 2018-06-20 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Privilegios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduloNCod', models.CharField(max_length=45)),
                ('moduloNombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ModUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Privilegios.Modulos')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolesNCod', models.CharField(max_length=45)),
                ('rolesNombre', models.CharField(max_length=45)),
                ('rolesViatura', models.CharField(max_length=10, unique=True)),
                ('modulos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Privilegios.Modulos')),
            ],
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Privilegios.Roles')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='privilegios',
            name='modulos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Privilegios.Modulos'),
        ),
    ]
