# Generated by Django 2.0.4 on 2018-06-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Privilegios', '0002_auto_20180620_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilegios',
            name='privilegioCod',
        ),
    ]
