# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cargo', '0001_initial'),
        ('Privilegios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajadorCod', models.CharField(max_length=20, unique=True)),
                ('trabajadorEstado', models.CharField(choices=[('A', 'activo'), ('I', 'inactivo')], max_length=1)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cargo.Cargo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Persona.Persona')),
                ('privilegios', models.ManyToManyField(to='Privilegios.Privilegios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
