# Generated by Django 2.0.6 on 2018-06-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0001_initial'),
        ('Trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Sucursal.Sucursal'),
        ),
    ]
