# Generated by Django 2.0.6 on 2018-06-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajador', '0002_trabajador_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Persona.Persona'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='trabajadorEstado',
            field=models.CharField(max_length=1),
        ),
    ]
