# Generated by Django 2.0.6 on 2018-06-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajador', '0003_auto_20180621_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='privilegios',
        ),
    ]
