# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaNombres', models.CharField(max_length=50)),
                ('personaApellidos', models.CharField(max_length=50)),
                ('personaDni', models.CharField(max_length=8, unique=True)),
                ('personaTelefono', models.CharField(max_length=9, null=True)),
                ('personaEmail', models.EmailField(max_length=254)),
                ('personaEstado', models.CharField(choices=[('A', 'activo'), ('I', 'inactivo')], max_length=1)),
            ],
        ),
    ]
