# Generated by Django 2.0.7 on 2018-07-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='personaDni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='personaEstado',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
