# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCod', models.CharField(max_length=20, unique=True)),
                ('areaDescripcion', models.CharField(max_length=80, unique=True)),
                ('areaEstado', models.CharField(choices=[('A', 'activo'), ('I', 'inactivo')], max_length=1)),
            ],
        ),
    ]
