# Generated by Django 2.0.4 on 2018-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='areaEstado',
            field=models.CharField(max_length=1),
        ),
    ]
