# Generated by Django 2.0.6 on 2018-06-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargo', '0003_auto_20180621_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Area.Area'),
        ),
    ]
