# Generated by Django 2.0.4 on 2018-06-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursalCod', models.CharField(max_length=15, unique=True)),
                ('sucursalDescripcion', models.CharField(max_length=50)),
                ('sucursalDireccion', models.CharField(max_length=80)),
                ('sucursalReferencia', models.CharField(max_length=80)),
                ('sucursalLatitud', models.CharField(max_length=50)),
                ('sucursalLongitud', models.CharField(max_length=50)),
            ],
        ),
    ]
